language: python
python:
  - "3.7"
jobs:
  fast_finish: true
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - "flake8 --show-source --max-line-length=80 --statistics --builtins=_ common engine feed plugins"
script:
  - python test.py
  - docker build -t "$DOCKER_USERNAME"/code-server-python .
    if: branch = master
  - docker build -t "$DOCKER_USERNAME"/code-server-python:develop .
    if: branch = develop
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master