language: python
python:
  - "3.6"
  - "3.7"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
  fast_finish: true
sudo: required
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - "flake8 --show-source --max-line-length=80 --statistics --builtins=_ common engine feed plugins"
script:
  - python test.py
after_script:
  - docker build -t "$DOCKER_USERNAME"/code-server-python .